name: Deploy to Production Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /opt/erp-system
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          # python init_db.py  # Desabilitado em produção para proteger o banco de dados
          sudo systemctl restart erp-system
          echo "Deploy completed successfully!"
